Completed adjustments as needed for contact page.
byte-pushers/bp-web pull request #197
Opened 2021-02-15 19:32 UTC by ocampd1

2021-02-18 00:00 UTC, pouncilt requested changes

2021-02-18 00:00 UTC, pouncilt commented on bp-web-client/angular-app/src/app/app.module.ts
> +import {ContactButtonService} from './services/contact-button.service';
Spacing here.

2021-02-18 19:04 UTC, ocampd1 commented on package-lock.json
> +{
Was not actually included in any of the files. Decided to delete it instead

2021-02-18 19:04 UTC, ocampd1 commented on package.json
> +{}
Was not actually included in any of the files. Decided to delete it instead

2021-02-18 19:05 UTC, ocampd1 commented on bp-web-client/angular-app/src/app/components/app-home/app-home.component.ts
> +import {environment} from '../../../environments/environment';
Added spacing.

2021-02-18 19:05 UTC, ocampd1 commented on bp-web-client/angular-app/src/app/components/app-work/app-work.component.ts
> +import {environment} from '../../../environments/environment';
Added spacing.

2021-02-18 19:25 UTC, ocampd1 commented on bp-web-client/angular-app/src/app/services/contact-button.service.ts
> +public OnContactPage(notOnContact) {
refactored method to isOnContactView(notOnContactView: boolean): boolean

2021-02-18 21:21 UTC, ocampd1 commented on bp-web-client/angular-app/src/app/components/app-contact/app-contact.component.ts
> +              public scrollTo: ScrollService,
renamed to scrollToService

2021-02-18 21:21 UTC, ocampd1 commented on bp-web-client/angular-app/src/app/components/app-contact/app-contact.component.ts
> +              public onContact: ContactButtonService) {
renamed to contactButtonService

2021-02-18 21:21 UTC, ocampd1 commented on bp-web-client/angular-app/src/app/shared/components/app-footer/app-footer.component.html
> +      <div class="col-sm-4 footer-quote" style=" height: 120px;" *ngIf="this.isOnContact.notOnContact">
omitted this keyword entirely.

2021-02-18 21:21 UTC, ocampd1 commented on bp-web-client/angular-app/src/app/shared/components/app-footer/app-footer.component.html
> +      <div class="col-sm-4 footer-quote-mobile" style=" height: 120px;" *ngIf="this.isOnContact.notOnContact">
omitted .this keyword entirely.

2021-02-18 21:22 UTC, ocampd1 commented on bp-web-client/angular-app/src/app/shared/components/app-footer/app-footer.component.ts
> +  constructor(public isOnContact: ContactButtonService,
Made variables private and applied getters and setters for component.

2021-02-18 21:27 UTC, ocampd1 commented on bp-web-client/angular-app/src/app/app.module.ts
> +    {provide: Window, useValue: window},
removed line.

2021-02-18 21:31 UTC, ocampd1 commented on bp-web-client/angular-app/src/app/app.module.ts
> +import {ContactButtonService} from './services/contact-button.service';
Added spacing

2021-02-19 00:00 UTC, ocampd1 commented on bp-web-client/angular-app/src/app/services/scroll.service.ts
> +  constructor(public onContact: ContactButtonService) { }
removed from constructor, not used at all in service.

2021-02-19 00:01 UTC, ocampd1 commented on bp-web-client/angular-app/src/app/services/scroll.service.ts
> +import {ContactButtonService} from './contact-button.service';
Removed from service, not used at all.

2021-02-19 00:24 UTC, ocampd1 commented on bp-web-client/angular-app/src/app/shared/components/app-footer/app-footer.component.ts
> +              public scrollTo: ScrollService) { }
Renamed to ScrollToService.

2021-02-19 00:24 UTC, ocampd1 commented on bp-web-client/angular-app/src/app/shared/components/app-footer/app-footer.component.html
> +      <div class="col-sm-4 footer-quote-mobile" style=" height: 120px;" *ngIf="this.isOnContact.onContact">
done

2021-02-19 02:16 UTC, pouncilt approved these changes

2021-02-19 02:16 UTC, merged